# Custom Resource Definition (CRD)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacemigrations.migrations.internal
spec:
  group: migrations.internal
  names:
    plural: namespacemigrations
    singular: namespacemigration
    kind: NamespaceMigration
    shortNames:
      - nsmigration
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourceNamespace:
                  type: string
                targetNamespace:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
