---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-migration-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-migration-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["migrations.internal"]
    resources: ["namespacemigrations"]
    verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-migration-binding
subjects:
  - kind: ServiceAccount
    name: namespace-migration-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: namespace-migration-role
  apiGroup: rbac.authorization.k8s.io
