apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: example-configmap
        - secretRef:
            name: example-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: dev-ns
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: dev-ns
type: Opaque
data:
  DB_USER: dXNlcm5hbWU=  # base64 encoded "username"
  DB_PASS: cGFzc3dvcmQ=  # base64 encoded "password"
